
CREATE TABLE ADMINISTRATION (
                ID VARCHAR NOT NULL,
                PARAMETRE VARCHAR NOT NULL,
                VALEUR VARCHAR NOT NULL,
                PRIMARY KEY (ID)
);


CREATE TABLE ANNONCES (
                ID INT AUTO_INCREMENT NOT NULL,
                NOM VARCHAR NOT NULL,
                RANG INT NOT NULL,
                TELEPHONE INT NOT NULL,
                DESCRIPTION VARCHAR NOT NULL,
                VALIDATION BOOLEAN NOT NULL,
                ADRESSE_MAIL VARCHAR NOT NULL,
                ADRESSE VARCHAR NOT NULL,
                PRIMARY KEY (ID)
);

ALTER TABLE ANNONCES MODIFY COLUMN RANG INTEGER COMMENT 'Rang d''affichage sur la page';


CREATE TABLE REF_SECTIONS (
                ID INT AUTO_INCREMENT NOT NULL,
                LIBELLE VARCHAR NOT NULL,
                PRIMARY KEY (ID)
);


CREATE TABLE REF_PROMOTIONS (
                ID INT NOT NULL,
                ANNEE INT NOT NULL,
                PRIMARY KEY (ID)
);


CREATE TABLE REF_SEXES (
                ID INT NOT NULL,
                LIBELLE VARCHAR NOT NULL,
                PRIMARY KEY (ID)
);


CREATE TABLE STATUTS (
                ID INT NOT NULL,
                LIBELLE VARCHAR NOT NULL,
                PRIMARY KEY (ID)
);


CREATE TABLE REF_ETABLISSEMENTS (
                ID INT AUTO_INCREMENT NOT NULL,
                NOM VARCHAR NOT NULL,
                COMMUNE VARCHAR NOT NULL,
                PRIMARY KEY (ID)
);


CREATE TABLE REF_FILIAIRES (
                ID INT AUTO_INCREMENT NOT NULL,
                NOM VARCHAR NOT NULL,
                PRIMARY KEY (ID)
);


CREATE TABLE X (
                ID INT NOT NULL,
                ID_SEXE INT NOT NULL,
                ID_SECTION INT NOT NULL,
                ADRESSE_MAIL VARCHAR NOT NULL,
                ID_FILIERE INT NOT NULL,
                ID_PROMOTION INT NOT NULL,
                ID_ETABLISSEMENT INT NOT NULL,
                PRIMARY KEY (ID)
);

ALTER TABLE X MODIFY COLUMN ID INTEGER COMMENT 'Issue du ldap';


CREATE TABLE SERIES (
                ID INT AUTO_INCREMENT NOT NULL,
                NUMERO INT NOT NULL,
                DATE_DEBUT DATETIME NOT NULL,
                DATE_FIN DATETIME NOT NULL,
                PRIMARY KEY (ID)
);


CREATE TABLE L_X_SERIES (
                ID INT NOT NULL,
                ID_X INT NOT NULL,
                ID_SERIE INT NOT NULL,
                PRIMARY KEY (ID)
);

ALTER TABLE L_X_SERIES COMMENT 'Disponiblités de l''X quant aux différentes séries';


CREATE TABLE ADMISSIBLES (
                ID INT NOT NULL,
                NOM VARCHAR(50) NOT NULL,
                PRENOM VARCHAR(50) NOT NULL,
                ID_SEXE INT NOT NULL,
                ADRESSE_MAIL VARCHAR NOT NULL,
                ID_SERIE INT NOT NULL,
                ID_FILIAIRE INT NOT NULL,
                ID_ETABLISSEMENT INT NOT NULL,
                PRIMARY KEY (ID)
);

ALTER TABLE ADMISSIBLES COMMENT 'Tables contenant les admissibles à l''école polytechnique';


CREATE TABLE DEMANDES (
                ID INT NOT NULL,
                ID_ADMISSIBLE INT NOT NULL,
                ID_X INT NOT NULL,
                LIEN VARCHAR NOT NULL,
                ID_STATUS INT NOT NULL,
                PRIMARY KEY (ID)
);

ALTER TABLE DEMANDES MODIFY COLUMN LIEN VARCHAR COMMENT 'Lien en get (code unique)
';


ALTER TABLE X ADD CONSTRAINT ref_sections_x_fk
FOREIGN KEY (ID_SECTION)
REFERENCES REF_SECTIONS (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE X ADD CONSTRAINT ref_promotions_x_fk
FOREIGN KEY (ID_PROMOTION)
REFERENCES REF_PROMOTIONS (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ADMISSIBLES ADD CONSTRAINT ref_sexes_admissibles_fk
FOREIGN KEY (ID_SEXE)
REFERENCES REF_SEXES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE X ADD CONSTRAINT ref_sexes_x_fk
FOREIGN KEY (ID_SEXE)
REFERENCES REF_SEXES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DEMANDES ADD CONSTRAINT statuts_demandes_fk
FOREIGN KEY (ID_STATUS)
REFERENCES STATUTS (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ADMISSIBLES ADD CONSTRAINT ref_etablissements_admissibles_fk
FOREIGN KEY (ID_ETABLISSEMENT)
REFERENCES REF_ETABLISSEMENTS (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE X ADD CONSTRAINT ref_etablissements_x_fk
FOREIGN KEY (ID_ETABLISSEMENT)
REFERENCES REF_ETABLISSEMENTS (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ADMISSIBLES ADD CONSTRAINT ref_filiaires_admissibles_fk
FOREIGN KEY (ID_FILIAIRE)
REFERENCES REF_FILIAIRES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE X ADD CONSTRAINT ref_filiaires_x_fk
FOREIGN KEY (ID_FILIERE)
REFERENCES REF_FILIAIRES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE L_X_SERIES ADD CONSTRAINT x_l_x_series_fk
FOREIGN KEY (ID_X)
REFERENCES X (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DEMANDES ADD CONSTRAINT x_demandes_fk
FOREIGN KEY (ID_X)
REFERENCES X (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ADMISSIBLES ADD CONSTRAINT series_admissibles_fk
FOREIGN KEY (ID_SERIE)
REFERENCES SERIES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE L_X_SERIES ADD CONSTRAINT series_l_x_series_fk
FOREIGN KEY (ID_SERIE)
REFERENCES SERIES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DEMANDES ADD CONSTRAINT admissibles_demandes_fk
FOREIGN KEY (ID_ADMISSIBLE)
REFERENCES ADMISSIBLES (ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
